[env:cool-bed-tb6612]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs

lib_deps =
	tzapu/WiFiManager @ ^2.0.17
	esphome/ESPAsyncWebServer-esphome @ ^3.3.0
	ottowinter/ESPAsyncTCP-esphome @ ^2.0.0
	bblanchon/ArduinoJson @ ^7.2.0
	wollewald/INA226_WE @ ^1.2.9
	paulstoffregen/OneWire @ ^2.3.8
	milesburton/DallasTemperature @ ^3.11.0
	sparkfun/SparkFun TB6612FNG Arduino Library @ ^1.0.1
	knolleary/PubSubClient @ ^2.8

build_flags =
	-D FLOW_SENSOR_PIN=15
	-D BUTTON_PIN=0
	-D DALLAS_SENSOR_RETURNING_PIN=5
	-D DALLAS_SENSOR_OUTGOING_PIN=18
	-D MOTOR_DRIVER_PWM_PIN=27
	-D MOTOR_DRIVER_TB6612_AIN1_PIN=12
	-D MOTOR_DRIVER_TB6612_AIN2_PIN=13
	-D MOTOR_DRIVER_TB6612_STBY_PIN=14
	-D RED_LED_PIN=26
	-D GREEN_LED_PIN=25
	-D BUILTIN_LED_PIN=2

[env:cool-bed-pwm]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs

lib_deps =
	tzapu/WiFiManager @ ^2.0.17
	esphome/ESPAsyncWebServer-esphome @ ^3.3.0
	ottowinter/ESPAsyncTCP-esphome @ ^2.0.0
	bblanchon/ArduinoJson @ ^7.2.0
	wollewald/INA226_WE @ ^1.2.9
	paulstoffregen/OneWire @ ^2.3.8
	milesburton/DallasTemperature @ ^3.11.0
	knolleary/PubSubClient @ ^2.8

build_flags =
	-D FLOW_SENSOR_PIN=15
	-D BUTTON_PIN=0
	-D DALLAS_SENSOR_RETURNING_PIN=5
	-D DALLAS_SENSOR_OUTGOING_PIN=18
	-D MOTOR_DRIVER_PWM_PIN=27
	-D RED_LED_PIN=26
	-D GREEN_LED_PIN=25
	-D BUILTIN_LED_PIN=2
