[platformio]
extra_configs = platformio.local.ini ; define OTA here, see .local.sample.ini for details

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
board_build.filesystem = spiffs

lib_deps =
	tzapu/WiFiManager @ ^2.0.17
	esphome/ESPAsyncWebServer-esphome@^3.4.0 # https://registry.platformio.org/libraries/esphome/ESPAsyncWebServer-esphome
	esphome/AsyncTCP-esphome@^2.1.4 # https://registry.platformio.org/libraries/esphome/AsyncTCP-esphome
	bblanchon/ArduinoJson @ ^7.2.0
	wollewald/INA226_WE @ ^1.2.9
	paulstoffregen/OneWire @ ^2.3.8
	milesburton/DallasTemperature @ ^3.11.0
	knolleary/PubSubClient @ ^2.8 # https://registry.platformio.org/libraries/knolleary/PubSubClient

build_unflags = -std=gnu++11
build_flags =
	-std=gnu++14
	-D FW_VERSION=\"0.1.0\"
	-D SERIAL_BAUD=${env.monitor_speed}

# Cool Bed Prototype V1 board
[env:cool-bed-pt-v1-usb]
upload_protocol = esptool
lib_deps =
	${env.lib_deps}
	sparkfun/SparkFun TB6612FNG Motor Driver Library@^1.0.0 # https://registry.platformio.org/libraries/sparkfun/SparkFun%20TB6612FNG%20Motor%20Driver%20Library
build_flags =
	${env.build_flags}
	-D FLOW_SENSOR_PIN=15
	-D BUTTON_PIN=0
	-D DALLAS_SENSOR_RETURNING_PIN=5
	-D DALLAS_SENSOR_OUTGOING_PIN=18
	-D DALLAS_SENSOR_COOLING_PIN=19
	-D CIRCULATION_PWM_PIN=27 # with a TB6612
	-D CIRCULATION_TB6612_AIN1_PIN=12
	-D CIRCULATION_TB6612_AIN2_PIN=13
	-D CIRCULATION_TB6612_STBY_PIN=14
	-D COOLING_PWM_PIN=33 # with a DRV886
	-D HEATING_PWM_PIN=23 # with an external LR7843 MOSFET driver
	-D RED_LED_PIN=26
	-D GREEN_LED_PIN=25
	-D BUILTIN_LED_PIN=2
	-D INA226_CIRCULATION_ADDRESS=0x40

[env:cool-bed-pt-v1-ota]
extends = env:cool-bed-pt-v1-usb
upload_protocol = espota
upload_flags =
	--port=${env.custom_ota_port}
	--auth=${env.custom_ota_password}
