; Use this sample to create a local-only PlatformIO overrides file.
; Name it platformio.local.ini so that it will be git-ignored.

; Define OTA password here (quote the string literal) if you want to use OTA.
; Define OTA_ENABLE_PIN here if you want to use a GPIO pin to allow OTA mode.
; Pull down to allow, pull up by default.
; An OTA enable pin is optional. If not defined, OTA mode will always be available when WiFi is connected.
; After changing this file, need to re-touch the main ini file for the IDE to pick up the changes.

[env]
custom_ota_password = change-me
custom_ota_port = 3232
build_src_flags =
	-D OTA_ENABLE
	-D OTA_PORT=${env.custom_ota_port}
	-D OTA_PASSWORD=\"${env.custom_ota_password}\"
	-D OTA_ENABLE_PIN=32
; note, use build_src_flags so not to conflict with build_flags in platformio.ini

[env:cool-bed-tb6612-ota]
upload_port = cool-bed.lan

[env:cool-bed-pwm-ota]
upload_port = cool-bed.lan
